services:
  backend:
    build:
      context: backend/app/
      dockerfile: docker/dev.Dockerfile
      target: builder
    ports:
      - "8400:80"
    configs:
      - app_config
    secrets:
      - app_secret
  
  # frontend:
  #   build:
  #     context: frontend/
  #     dockerfile: docker/dev.Dockerfile 
  #     target: builder
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./nerdz-ne/node_modules


configs:
  app_config:
    file: backend/app/app_config.py 
  other_config:
    external: true

secrets:
  app_secret:
    file: backend/app/app_secret.py