# docker-compose build --no-cache

services:
  log-test:
    build:
      context: log-test/app
      dockerfile: docker/Dockerfile
      target: builder
    ports:
      - "8000:8000"
    stop_signal: SIGINT # needed to Flask to stop gracefully instead of SIGTERM

  backend:
    build:
      context: backend/app/
      dockerfile: docker/dev.Dockerfile
      target: builder
    ports:
      - "8400:80"
    configs:
      - app_config
    secrets:
      - app_secret
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
  # frontend:
  #   build:
  #     context: frontend/
  #     dockerfile: docker/dev.Dockerfile 
  #     target: builder
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./nerdz-ng/node_modules

configs:
  app_config:
    file: backend/app/app_config.py 
  other_config:
    external: true

secrets:
  app_secret:
    file: backend/app/app_secret.py